#!/bin/sh

USER=$1
PASSWORD=$2

if [ -z "$USER" ] || [ -z "$PASSWORD" ]; then
	echo "Usage: install \$USER \$PASSWORD"
fi

cd $WEBROOT

occ maintenance:install --admin-user=$USER --admin-pass=$PASSWORD --database=$SQL --database-name=owncloud --database-host=$SQL --database-user=owncloud --database-pass=owncloud
