#!/bin/bash
OC_SOURCE="/srv/http/owncloud"
WORKDIR="/tmp/oc-docker"

SQL=$1
PORT=`python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'`
NAME="oc-$PORT";
SQL_PASS=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;`
 
mkdir -p "$WORKDIR/$NAME/data"
mkdir -p "$WORKDIR/$NAME/config"

PHP_VERSION=$2
PHP_VERSION=${PHP_VERSION:-5}

if [ "$PHP_VERSION" != "5" ] && [ "$PHP_VERSION" != "7" ]; then
	echo "invalid php version"
	exit
fi;

echo $BLACKFIRE_SERVER_TOKEN

BLACKFIRE_RUNNING=$(docker inspect --format="{{ .State.Running }}" blackfire 2> /dev/null)
BLACKFIRE_EXIT_CODE=$?
if [ -z "$BLACKFIRE_SERVER_TOKEN" ] && [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then # we either need the blackfire config or already have an existing container
	echo "Set \$BLACKFIRE_SERVER_TOKEN and \$BLACKFIRE_SERVER_ID to enable blackfire integration (https://blackfire.io/docs/integrations/docker)"
	LINK_BLACKFIRE=""
else
	# ensure blackfire agent is running
	if [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then
		docker run --name="blackfire" -d -e BLACKFIRE_SERVER_ID=$BLACKFIRE_SERVER_ID -e BLACKFIRE_SERVER_TOKEN=$BLACKFIRE_SERVER_TOKEN blackfire/blackfire
	elif [ "$BLACKFIRE_RUNNING" == "false" ]; then
		docker start blackfire
	fi;
	LINK_BLACKFIRE="--link blackfire:blackfire"
fi;

WEBROOT="/var/www/html"
VOLUMES="-v $OC_SOURCE:$WEBROOT -v $WORKDIR/$NAME/data:$WEBROOT/data -v $WORKDIR/$NAME/config:$WEBROOT/config"
DOCKER_IMAGE="icewind1991/owncloud-dev:$PHP_VERSION"

if [ "$SQL" = "mysql" ]; then
	docker run --name "$NAME-mysql" -e MYSQL_ROOT_PASSWORD=$SQL_PASS -e MYSQL_PASSWORD=owncloud -e MYSQL_USER=owncloud -e MYSQL_DATABASE=owncloud -d mysql:latest
	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-mysql:mysql" -e SQL=mysql $VOLUMES $DOCKER_IMAGE
	echo "$NAME,$NAME-mysql"
elif [ "$SQL" = "pgsql" ]; then
	docker run --name "$NAME-pgsql" -e POSTGRES_PASSWORD=owncloud -e POSTGRES_USER=owncloud -e POSTGRES_DATABASE=owncloud -d postgres:latest
	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-pgsql:pgsql" -e SQL=pgsql $VOLUMES $DOCKER_IMAGE
	echo "$NAME,$NAME-pgsql"
elif [ "$SQL" = "oci" ]; then
	docker run --name "$NAME-oci" -d wnameless/oracle-xe-11g
	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-oci:oci" -e SQL=oci $VOLUMES $DOCKER_IMAGE
	echo "$NAME,$NAME-oci"
else
	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE -e SQL=sqlite $VOLUMES $DOCKER_IMAGE
	echo "$NAME"
fi

echo "Running on http://localhost:$PORT" 
