#!/bin/bash

SQL=$1
PHP_VERSION=$2
EXTRA=$3
EXTRA_ARG=""

shift
shift

if [ "$EXTRA" = "s3" ] || [ "$EXTRA" = "azure" ] || [ "$EXTRA" = "azure" ]; then
    shift
    EXTRA_ARG=$EXTRA
fi

echo "Starting servers"
CONTAINERS=`ncserver $SQL $PHP_VERSION $EXTRA_ARG | tail -2 | head -1`

IFS=',' read -a CONTAINERS <<< "$CONTAINERS"

echo "Waiting for things to settle"
if [ "$SQL" = "" ] || [ "$SQL" = "sqlite" ]; then
	sleep 2 # less servers to wait for
elif [ "$SQL" = "oci" ]; then
	sleep 30 # oracle is always a bit lazy
else
	sleep 15
fi

echo "Starting tests"

docker exec ${CONTAINERS[0]} install admin admin
docker exec ${CONTAINERS[0]} tests $@

echo "Cleaning up"

docker kill ${CONTAINERS[0]} ${CONTAINERS[1]}
docker rm ${CONTAINERS[0]} ${CONTAINERS[1]}
