#!/bin/bash

SQL=$1

echo "Starting servers"
CONTAINERS=`ocserver $SQL | tail -2 | head -1`

IFS=',' read -a CONTAINERS <<< "$CONTAINERS"

echo "Waiting for things to settle"
sleep 10

echo "Starting tests"

docker exec ${CONTAINERS[0]} tests

echo "Cleaning up"

docker kill ${CONTAINERS[0]} ${CONTAINERS[1]}
docker rm ${CONTAINERS[0]} ${CONTAINERS[1]}